### ISSUE TITLE
First Homework

### ISSUE THREAD

**Issue by eyusufatik** [bounswe/bounswe2023group3#1]
@bounswe/bounswe2023group3

For our first homework, everyone should create an "about me page" on himself/herself and link to it under the team members list in the who we are page.

For the naming of these pages I suggest the format "About [Insert Name Here]" (e.g. About Esad Yusuf Atik)

Also everyone should pick a github repo and write about it in the research page under the wiki.

Please leave a comment when you finish your work and tick the box near your name.

- [x] Beyza Akçınar
- [x] Ozan Oytun Karakaya
- [x] Hatice Serra Hakyemez
- [x] Faruk Yıldırım
- [x] Sait Hızlı
- [x] Alp Tuna
- [x] Esad Yusuf Atik
- [x] Ali Üçer
- [x] Muhammet Batuhan İlhan
- [x] Batuhan Çetin
- [x] Simar Achmet Kechagia

**Comment by eyusufatik** [comment]
I've finished my work.
 
See [Research Page](https://github.com/bounswe/bounswe2023group3/wiki/Research) and [About Esad Yusuf Atik page](https://github.com/bounswe/bounswe2023group3/wiki/About-Esad-Yusuf-Atik)

**Comment by SaitHzl** [comment]
I've created my own page. [About Sait Hızlı](https://github.com/bounswe/bounswe2023group3/wiki/About-Sait-H%C4%B1zl%C4%B1) 

Also see Research Page. [Research Page](https://github.com/bounswe/bounswe2023group3/wiki/Research)

**Comment by ozankrkya** [comment]
I've also finished my work. 

You can view them as [About Ozan Oytun Karakaya](https://github.com/bounswe/bounswe2023group3/wiki/About-Ozan-Oytun-Karakaya) and [XSS Payload List Research](https://github.com/bounswe/bounswe2023group3/wiki/Research#xss-payload-list-by-payloadbox).

**Comment by HaticeSerraHakyemez** [comment]
I've completed my work.

They can be seen through the links [About Hatice Serra Hakyemez](https://github.com/bounswe/bounswe2023group3/wiki/About-Hatice-Serra-Hakyemez) and [tenserflow](https://github.com/bounswe/bounswe2023group3/wiki/Research#tensorflow).

**Comment by batuhancetin** [comment]
I've done my work.
You can see the links as [About Batuhan Çetin](https://github.com/bounswe/bounswe2023group3/wiki/About-Batuhan-%C3%87etin) and [Research Page](https://github.com/bounswe/bounswe2023group3/wiki/Research).

**Comment by Alputer** [comment]
I am also done with my work.
You can reach the links via [About Alp Tuna](https://github.com/bounswe/bounswe2023group3/wiki/About-Alp-Tuna) and [Flutter](https://github.com/bounswe/bounswe2023group3/wiki/Research#flutter)

**Comment by simarahmtkhy** [comment]
I have also completed my work.
You can check the links [About Simar Achmet Kechagia](https://github.com/bounswe/bounswe2023group3/wiki/About-Simar-Achmet-Kechagia) and [Research](https://github.com/bounswe/bounswe2023group3/wiki/Research)

**Comment by beyza-akcinar** [comment]
I am also done with my work.
You can see them through [About Beyza Akçınar](https://github.com/bounswe/bounswe2023group3/wiki/About-Beyza-Ak%C3%A7%C4%B1nar) and [Research](https://github.com/bounswe/bounswe2023group3/wiki/Research).

**Comment by aliucer** [comment]
I've done my work.
See [About Ali Üçer](https://github.com/bounswe/bounswe2023group3/wiki/About-Ali-%C3%9C%C3%A7er) and [Research](https://github.com/bounswe/bounswe2023group3/wiki/Research).

**Comment by farukyld** [comment]
I am also done with mine:
[About Faruk Yıldırım](https://github.com/bounswe/bounswe2023group3/wiki/About-Faruk-Y%C4%B1ld%C4%B1r%C4%B1m)
[Logisim Evolution](https://github.com/bounswe/bounswe2023group3/wiki/Research#Logisim-Evolution)
