### ISSUE TITLE
Requirement Revision

### ISSUE THREAD

**Issue by batuhancetin** [bounswe/bounswe2023group3#117]
All team members must analyze the project requirements. Revisions to the requirements can be done if it is needed.

**Comment by Alputer** [comment]
We forgot to add logout feature for moderators. I added this to our requirements.

**Comment by mberkturgut** [comment]
Requirement 2.7.1 is removed due to ambiguity

**Comment by berkecaliskan** [comment]
Requirement to authenticate the moderators has been added

**Comment by mberkturgut** [comment]
Username registration is unanimously decided for requirement 1.1.2

**Comment by BatuhanIlhan** [comment]
Change password and reset password functionalities were missing. Added.

**Comment by BatuhanIlhan** [comment]
Email verification was missing. Added.

**Comment by mberkturgut** [comment]
Requirement review is finalized by the team in the lab hour.
