### ISSUE TITLE
Research on Flutter

### ISSUE THREAD

**Issue by berkecaliskan** [bounswe/bounswe2023group3#128]
The mobile app team should research on Flutter to start implementing the mobile app

**Comment by simarahmtkhy** [comment]
We got familiar with flutter. We followed this tutorial https://youtube.com/playlist?list=PL4cUxeGkcC9jLYyp2Aoh6hcWuxFDX6PBJ&si=7v0XQA8eZqJK_9ZA. Also we used the flutter documentation for further details (https://docs.flutter.dev/)
