### ISSUE TITLE
Create a project glossary

### ISSUE THREAD

**Issue by Alputer** [bounswe/bounswe2023group3#13]
In order to make the discussions more efficient and ensure that everyone is on the same page, creating a glossary for frequently used terms related to the project can be quite helpful.

**Comment by eyusufatik** [comment]
I believe we should provide a clear definition for prediction power score. What is it? What effects does it have? etc.

**Comment by Alputer** [comment]
Yes, you are right. We can actually discard the term "prediction power score" and stick to "rating", since it is clearer and leads to less ambigouity.

**Comment by Alputer** [comment]
We created the first version of the glossary. You can view it in the [requirements specification.](https://github.com/bounswe/bounswe2023group3/wiki/Software-Requirements-Speci%EF%AC%81cation)
Right now, this glossary suffices the needs of the projects. Thus, I'm closing the issue
