### ISSUE TITLE
Who We Are page on Wiki is out of date

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2023group3#135]
[Who We Are](../wiki/Who-We-Are) page on Wiki (accessible through the sidebar) is out of date and should be updated with new members.

Going slightly beyond the scope of this issue: We may also want to distinguish currently active members from the legacy members in the meantime.

**Comment by farukyld** [comment]
we seperated old members into a new section. and add new members to our [who we are](https://github.com/bounswe/bounswe2023group3/wiki/Who-We-Are) page
