### ISSUE TITLE
Reviewing Use Case Diagram

### ISSUE THREAD

**Issue by mberkturgut** [bounswe/bounswe2023group3#137]
Use Case diagram shall be reviewed in accordance with the altered requirements.

**Comment by beyza-akcinar** [comment]
Our use case diagram was revised and new use cases were added considering the changes in our requirements 1.3.7 to 1.3.9. You can see our revised Use Case Diagram [here](https://github.com/bounswe/bounswe2023group3/wiki/Use-Case-Diagram).
