### ISSUE TITLE
Decide on a design palette

### ISSUE THREAD

**Issue by HaticeSerraHakyemez** [bounswe/bounswe2023group3#144]

**Comment by mberkturgut** [comment]
We shall decide on primary colors to use to create coherence. After deciding on the general design, we can decide on a general color & size ratio for buttons, labels etc. for home page, poll creation page and so on

**Comment by beyza-akcinar** [comment]
After voting among chosen candidate palettes by our members, we decided to use the highest voted colors and and their monochrome variants as our design palette. While making this decision, we considered the informative and social aspects of our application.
