### ISSUE TITLE
Remove ambiguities in requirements

### ISSUE THREAD

**Issue by eyusufatik** [bounswe/bounswe2023group3#17]
> Platform should have a section called "popular" which shows the most popular polls in the platform.

How is popular defined? Is it the most liked poll or is it the poll that received the most answers? A combination of both maybe?

>Platform shall include a ranking system based on general and tag specific ratings.

Is this based on prediction power score? If not how is it any different than prediction power score? The more frequently someone is right on polls, the more prediction power score they'll have thus getting them a higher rank in the system, or are we planning something else?

**Comment by Alputer** [comment]
I guess details of the popular section are to be determined. There might be several different approaches and we can determine them at the design or implementation phase.

I believe that, we should remove the phrase "prediction power score" completely with "rating", this would eliminate the confusion. What we mean is nothing special or complicated, simply rating.

**Comment by Alputer** [comment]
After our discussion during the team meeting, we decided the keywords to be defined in our project and added consequently created a glossary for confusing words. We also went over the requirements specification a few times and adjusted accordingly, so currently the ambiguity issue seems to be solved. Therefore, I'm closing the issue.
