### ISSUE TITLE
Complete Milestone 1 Report

### ISSUE THREAD

**Issue by beyza-akcinar** [bounswe/bounswe2023group3#188]
Our team needs to complete the Milestone 1 Report before the deadline.

**Comment by HaticeSerraHakyemez** [comment]
Additionally, individual contribution reports and software pre-release should be completed.

**Comment by batuhancetin** [comment]
Completed on 02.11.2023 thursday before deadline. You can reach from [here](https://github.com/bounswe/bounswe2023group3/wiki/Milestone-1-Review).
