### ISSUE TITLE
Preparing for the Milestone 1 Presentation

### ISSUE THREAD

**Issue by beyza-akcinar** [bounswe/bounswe2023group3#190]
We chose representatives from each group to prepare for the upcoming Milestone presentation. This process includes preparing for possible questions related to their group's work and our project roadmap.

**Comment by mberkturgut** [comment]
@berkecaliskan @batuhancetin I suggest we hold a session to review & practice our presentation before the milestone day. It would also be nice to get input from other available team members during this session. What do you think?
