### ISSUE TITLE
Implement Other's Profile View

### ISSUE THREAD

**Issue by HaticeSerraHakyemez** [bounswe/bounswe2023group3#278]
Create the profile view for others using the template of own profile page.

**Comment by HaticeSerraHakyemez** [comment]
I implemented the page template [here](https://github.com/bounswe/bounswe2023group3/pull/298). @aliucer you can continue improving its design and manually entered data for now.

**Comment by aliucer** [comment]
made some improvement and moved inline CSS to external classes
