### ISSUE TITLE
Reviewing Our Work According to Milestone 1 Feedback

### ISSUE THREAD

**Issue by HaticeSerraHakyemez** [bounswe/bounswe2023group3#280]
- Improve user and home page designs.
- ~~Review URL access permissions.~~ (This will be done before milestone 2, we decided to do this after most of our page templates are done so that we can test the designs more easily.)
- Ensure login, register and forgot-password mechanisms. 
- Improve welcome page design.
- ~~Include logo of the app.~~ (We haven't decided on the logo yet. It will be added before milestone 2)
- ~~Implement the connections between poll creation request page and the backend.~~ (We are waiting for the backend to complete their poll implementation. The connections will be handled till the 21st of November.)
- Improve button colors.
- Add app header (including application name and logo) to the common app.html file.

**Comment by HaticeSerraHakyemez** [comment]
I made some small improvements [here](https://github.com/bounswe/bounswe2023group3/pull/298), such as: modifying margins, changing poll filter options to buttons (following, trending, created, liked...), slight change in some button colors. I also tried adding header and footer to every page in the app, but I couldn't resolve some issues related to this, I hope @mberkturgut or @beyza-akcinar can try to implement it as well.

**Comment by beyza-akcinar** [comment]
Header component is created and added to all pages. In addition, I made overall design adjustments (on colors, page layout, etc) on all pages. I also ensured login, register and forgot-password mechanisms. You can see the changes here #332.
