### ISSUE TITLE
Modifying Our Code According to Prettier Format

### ISSUE THREAD

**Issue by HaticeSerraHakyemez** [bounswe/bounswe2023group3#281]
Our code so far should be modified according to the prettier format as we specified [before](https://github.com/bounswe/bounswe2023group3/wiki/Lab-report-3#implementation-strategies).

**Comment by mberkturgut** [comment]
Prettier package is installed, and code format is updated according to 

``
{
  "singleQuote": true,
  "semi": false,
  "tabWidth": 2,
  "printWidth": 80
}
``

For the future please run `npm run format` before pushing your code or use auto save tool in VS Code as described in [here](https://medium.com/@victormejia/setting-up-prettier-in-an-angular-cli-project-2f50c3b9a537)
