### ISSUE TITLE
Creating UML Class Diagrams

### ISSUE THREAD

**Issue by simarahmtkhy** [bounswe/bounswe2023group3#31]
In the meeting that took place yesterday(05.04.2023), we have determined the draft of our class diagrams and agreed on the structure as a group. We will create the diagram on online drawing tools.

**Comment by Alputer** [comment]
We created the class diagram using draw.io. It is published right now, you can find it on our wiki page, or just click [here](https://github.com/bounswe/bounswe2023group3/wiki/Class-Diagram)
