### ISSUE TITLE
Implement Data Connections

### ISSUE THREAD

**Issue by HaticeSerraHakyemez** [bounswe/bounswe2023group3#325]

**Comment by HaticeSerraHakyemez** [comment]
[Here](https://github.com/bounswe/bounswe2023group3/pull/342) I implemented poll lists, and while doing that I added some data connections related to polls. I can give you some notes about which connections need more urgent attention:
- Side bar user info
- Own profile user info
- Other's profile user info
- Badges
- Ranks
- Follower Number and Information
- Vote number in poll / Connection between selected option and increasing its value in the backend

**Comment by mberkturgut** [comment]
Thanks @HaticeSerraHakyemez , I will make sure to prioritize those

**Comment by HaticeSerraHakyemez** [comment]
It seems that some of the entities I mentioned are not implemented by the backend yet, we can add these connections later on.

**Comment by mberkturgut** [comment]
I contacted with the backend team and they will provide necessary implementations for retrieving the user info shortly. Then I will go on with those tasks.

**Comment by mberkturgut** [comment]
@HaticeSerraHakyemez you can find the related pull request here #400 
Incomplete user implementations will be completed under #399
