### ISSUE TITLE
Implement Poll Filtering

### ISSUE THREAD

**Issue by beyza-akcinar** [bounswe/bounswe2023group3#375]
We need to implement filtering for polls according to by trending-following, by creator, by ongoing-settled characteristics of the poll.

**Comment by HaticeSerraHakyemez** [comment]
[Here](https://github.com/bounswe/bounswe2023group3/pull/402) I implemented some of the filters and also the tag page. Filters will be completed later on a different PR.

**Comment by HaticeSerraHakyemez** [comment]
Settled, ongoing, trending, following, created and tag filters are enough for this milestone and they are all implemented so this issue will be closed with the linked PR. Later liked and voted poll filters will be added when backend is fully formed on this context.
