### ISSUE TITLE
Milestone 1 Report

### ISSUE THREAD

**Issue by HaticeSerraHakyemez** [bounswe/bounswe2023group3#38]

**Comment by aliucer** [comment]
We met with @HaticeSerraHakyemez and added table of contents, executive summary, project status, future plans, status of deliverables, evaluation of tools and processes to the Milestone 1 Report

**Comment by eyusufatik** [comment]
Please add scenarios to the deliverables section.

**Comment by Alputer** [comment]
Good job everyone! Our milestone report is ready and now you can view it through this [link](https://github.com/bounswe/bounswe2023group3/wiki/Milestone-1-report)
