### ISSUE TITLE
Reviewing Our Work After Milestone 2 Feedbacks

### ISSUE THREAD

**Issue by HaticeSerraHakyemez** [bounswe/bounswe2023group3#489]
Some of the work that should be done:
(This may extend to two weeks, not all things **must** be done within this week.)
You can open issues for the works you assign to yourself, this issue is an issue for self task assignment.

**Beyza**
- ~Add name surname inputs to user register~
- ~Comment deletion~
- Pending requests page instead of notifications
- Change side bars
- Add moderator apply page
- ~Link verification page~
- ~Implement settled poll design~
- Moderator data connections 
- ~Delete tag, delete option~
- ~~Add user name to side bar~~

**Serra**
- ~~Comment count~~
- ~~Like icon and count~~ 
- ~~Poll delete, report poll, send outcome verification request for own poll~~
-  ~~Add date info to polls.~~
- ~~Improve tag bar, redirect~~
- ~~Deadline with hour, infinite deadline~~
- ~~Add guest/blurry segments~~
- ~~Send outcome verification request~~
- ~~Link and improve moderator poll view page~~
- ~~Edit profile --> change name~~
- ~~Change all viewed polls to approved ones~~
- ~~Change password from settings~~
- ~~Add date info to comments~~

**Berk**
- Moderator should be able to modify tags
- Add sectioning (for example when "liked" polls are selected, user should be able to distinguish that they are seeing the liked polls)
- Add moderator feedback/response and deliver to user
- Tag choice as dropdown

**Ali**
- Annotations for badges
- Add more poll and users

**More**
- Fix console error messages

**Comment by aliucer** [comment]
I can have the following implementations for the week
Annotations for badges
Add more poll and users
Add date info to comments

**Comment by HaticeSerraHakyemez** [comment]
The tasks listed here have either been implemented or have been planned, so I'm closing this issue.
