### ISSUE TITLE
visual improvements 

### ISSUE THREAD

**Issue by farukyld** [bounswe/bounswe2023group3#679]
We can open an issue about the specific visual improvement and mention here

**Comment by farukyld** [comment]
those are the things comes to my mind:
- date time on the polls (decimal place)
- the strong pink color of the moderator approve feed
- put lines (or something to show the separation) between polls in the feed
- comment widget color

**Comment by farukyld** [comment]
![image](https://github.com/bounswe/bounswe2023group3/assets/120921965/cae95111-7bb9-4495-a55e-987f6c99f852)

**Comment by farukyld** [comment]
![image](https://github.com/bounswe/bounswe2023group3/assets/120921965/9b0fc624-e0d9-4484-b184-51b0fd4375e7)

**Comment by simarahmtkhy** [comment]
Changed the pink color to navy in https://github.com/bounswe/bounswe2023group3/pull/718

**Comment by simarahmtkhy** [comment]
Fixed the DateTime format in https://github.com/bounswe/bounswe2023group3/pull/723/files

**Comment by farukyld** [comment]
see #589 for comment widget color

**Comment by farukyld** [comment]
see #768 for putting lines and tag colors
