### ISSUE TITLE
Make search results clickable and reroute to that users profile

### ISSUE THREAD

**Issue by berkecaliskan** [bounswe/bounswe2023group3#685]

**Comment by farukyld** [comment]
You can use `ClickableUserName` widget under `views/pollView/clickableUserName.dart`. I have already used it inside `UserInformationWidget`. (`views/pollView/userInformationWidget.dart`)

**Comment by farukyld** [comment]
and also you can use this widget for profile photos. it shows a default photo in case of an empty profile photo link: 
![image](https://github.com/bounswe/bounswe2023group3/assets/120921965/bf64a9fa-99f1-4aa8-a911-1c6601c4f94b)

here an example usage:
![image](https://github.com/bounswe/bounswe2023group3/assets/120921965/c1dd0678-4b32-4085-9fd1-ee084b3c0557)
