### ISSUE TITLE
Requirements Discussion Phase 1

### ISSUE THREAD

**Issue by Alputer** [bounswe/bounswe2023group3#7]
Requirements are one of the most fundamental parts of a project, therefore in this issue we discuss and determine the requirements of our project. However, there might and probably will be some modifications to the requirements during the course. Therefore this issue is named as Phase 1.

**Comment by Alputer** [comment]
I came up with the following requirement. 

1) Our platform should include tags.

Description:

All predictions should have tags associated and users should be able to filter predictions according to tags. This will help us categorize the platform so that related information stays together. We may further discuss which tags to include but there are already some wiki pages that contain tag graphs which might be quite useful as our TA Utkan mentioned.

**Comment by Alputer** [comment]
2) We should have a rating system and an associated rating algorithm

To make the platform more entertaining and appealing for users, we should have a rating system. As users make correct predictions, their ratings increase and vice versa. Amount of the change in the ratings should depend on the rating algorithm. Therefore our rating system should have a sophisticated algorithm based on many factors. Whether it is based on the difficulty of the prediction, activeness of the user, current ratio of answers, current rating of the user, tags and type of the questions are already good candidate factors for that algorithm. Details should be definitely discussed further.

**Comment by Alputer** [comment]
4) Our platform should include a ranking based on ratings specific to tag ratings and general ratings.

Nowadays, many platforms, where users have ratings, include a ranking system. Based on the range of the ratings, we may also have different statuses for users just like the titles in chess. We can also have a section called "hall of fame" where best ratings in the history of the platform can be shown.

**Comment by simarahmtkhy** [comment]
> I came up with the following requirements:
> 
> 1. Our platform should include tags.
> 
> Description:
> 
> All predictions should have tags associated and users should be able to filter predictions according to tags. This will help us categorize the platform so that related information stays together. We may further discuss which tags to include but there are already some wiki pages that contain tag graphs which might be quite useful as our TA Utkan mentioned.

5. Having specific tags for each prediction poll will also help us in the rating system. The tags should be events that have objective outcomes so that our algorithm can check the accuracy of the prediction. So our system should not allow subjective topics that do not have deterministic outcomes.

**Comment by Alputer** [comment]
Since we discussed  enough about the platform structure and have a good starting point, I close this issue.
